### PR TITLE
fix:: any type is repeated

### PR DESCRIPTION
**Pull request by ahaoboy**
If the type is automatically generated, please close this pr

### CODE REVIEW

**Comment by thornbill** [comment]
Everything in `generated-client` is automatically generated. Note the comment at the top of the file:

> NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
> Do not edit the class manually.

**Comment by ahaoboy** [comment]
> Everything in `generated-client` is automatically generated.

Is this type problem caused by the generate tool?
I want to use rust to implement some jellyfin related libraries. Can this generator generate rust code like serde-jellyfin?

**Comment by thornbill** [comment]
I have no idea what serde-jellyfin is, but there are plenty of client generators for openapi schemas. The one used for this project (currently) is from here: https://openapi-generator.tech/docs/generators... but there are completely different generators out there also.

**Comment by oddstr13** [comment]
From a quick search I found a few alternatives;
- https://lib.rs/crates/progenitor
- https://docs.rs/openapi_lib_generator/latest/openapi_lib_generator/
- https://www.shuttle.rs/blog/2024/04/04/using-openapi-rust#generating-rust-from-openapi-specifications

I don't have any experience with any of them, best of luck :)

**Comment by ahaoboy** [comment]
> I have no idea what serde-jellyfin is

serde is a library for serialization and deserialization in Rust. There seems to be no official binding at present. I tried openapi, which can convert Rust code. Do you consider officially supporting jellyfin-sdk-rust?

And the automatically generated ts is a bit old? The ts code I generated using the latest openapi is slightly different

**Comment by thornbill** [comment]
The code is not old (it's generated from a current version of the openapi spec) but the generator version used is older. The last time I tried updating the generator version it produced broken code.

**Pull request closed without merging**
