### PR TITLE
Prepare for v0.11.0 release

### PR DESCRIPTION
**Pull request by thornbill**
*  Updates README with release notes
* Bumps version to 0.11.0

### CODE REVIEW

**Review by nielsvanvelzen — APPROVED** [review]
Doesn't this need bumping?

https://github.com/jellyfin/jellyfin-sdk-typescript/blob/master/src/versions.ts#L11

**Comment by thornbill** [comment]
I'm not aware of any breaking API changes...

**Comment by nielsvanvelzen** [comment]
I did bump it for the Kotlin SDK but unfortunately my PR doing so doesn't have much detail. I thought there are a few smaller changes that could be considered breaking but those might only be an issue in the Kotlin SDK because the JSON serializer is very strict.

**Comment by thornbill** [comment]
I'm in favor of letting it ride since we try to support the last major version in web. If an issue is encountered we can deal with it in a patch release. :man_shrugging:

**Comment by nielsvanvelzen** [comment]
Sounds good to me!

**Pull request merged**
